version: '3.8'
services:
  cache:
    image: redis:6.2.5-alpine
    restart: always
    command: redis-server --requirepass xxx_redis_password
    ports:
     - '6381:6379'
    environment:
     - REDIS_REPLICATION_MODE=master
    volumes:
     - streakpoints-redis:/var/lib/redis
  db:
    image: mysql:8
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: 'streakpoints'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'xxx_user_password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'xxx_root_password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'
    # Where our data will be persisted
    volumes:
      - streakpoints-mysql:/var/lib/mysql
volumes:
  streakpoints-redis:
  streakpoints-mysql:
